#! /bin/bash

sxhkd &
picom -b

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config normal_border_color  '#141415'
bspc config focused_border_color '#B01F1D'
bspc config top_padding 	10
bspc config bottom_padding 	10
bspc config left_padding 	10
bspc config right_padding 	10

bspc config honor_size_hints	true

bspc config window_gap          10

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	false

bspc config ignore_ewmh_focus 		false

bspc rule -a kitty state=floating rectangle=600x340+300+200
bspc rule -a mimfetch state=floating rectangle = 675x355+14+50
bspc rule -a keys state=floating rectangle = 600x690+20+50
bspc rule -a firefoxdeveloperedition state=floating rectangle=650x690+14+50
bspc rule -a 'Atom' state=floating rectangle=650x690+20+50

feh --bg-scale ~/Documents/Pictures/wp4.png --no-fehbg &
#hsetroot -add '#FF7349' -add '#AF3309' -add '#A82126' -add '#631009' -grad>

~/.config/polybar/launch.sh &
